/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Report that the process is running.
         */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Check the local database and evidence directory.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evidence Package
         * @description Return metadata for one stored evidence package.
         */
        get: operations["get_evidence_package_v1_evidence_packages__package_id__get"];
        /**
         * Upload Evidence Package
         * @description Validate and persist one immutable multipart evidence package.
         */
        put: operations["upload_evidence_package_v1_evidence_packages__package_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-packages/{package_id}/table-observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Package Table Observations
         * @description Return immutable table observations for one stored package.
         */
        get: operations["get_package_table_observations_v1_evidence_packages__package_id__table_observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-packages/{package_id}/video-snippet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evidence Video Snippet
         * @description Return the original bytes for one stored complete video snippet.
         */
        get: operations["get_evidence_video_snippet_v1_evidence_packages__package_id__video_snippet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pending-videos/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending Video
         * @description Return the durable receipt for one pending video.
         */
        get: operations["get_pending_video_v1_pending_videos__upload_id__get"];
        /**
         * Upload Pending Video
         * @description Stream, probe, and atomically publish one pending raw video.
         */
        put: operations["upload_pending_video_v1_pending_videos__upload_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repository-bundles/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repository Bundle
         * @description Return indexed metadata and current canonical member hashes.
         */
        get: operations["get_repository_bundle_v1_repository_bundles__recording_id__get"];
        /**
         * Upload Repository Bundle
         * @description Validate and atomically publish one repository bundle.
         */
        put: operations["upload_repository_bundle_v1_repository_bundles__recording_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round-analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Round Analysis
         * @description Validate and queue one analysis request.
         */
        post: operations["create_round_analysis_v1_round_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round-analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Round Analysis
         * @description Return one durable analysis status document.
         */
        get: operations["get_round_analysis_v1_round_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round-analyses/{analysis_id}/counterfactuals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Round Counterfactual
         * @description Synchronously create or reuse one immutable counterfactual.
         */
        post: operations["create_round_counterfactual_v1_round_analyses__analysis_id__counterfactuals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round-analyses/{analysis_id}/counterfactuals/{counterfactual_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Round Counterfactual
         * @description Return one immutable counterfactual from its runtime artifacts.
         */
        get: operations["get_round_counterfactual_v1_round_analyses__analysis_id__counterfactuals__counterfactual_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round-analyses/{analysis_id}/evidence-packages/{package_id}/frames/{part_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Round Analysis Frame
         * @description Return one validated JPEG frame scoped to a completed analysis.
         */
        get: operations["get_round_analysis_frame_v1_round_analyses__analysis_id__evidence_packages__package_id__frames__part_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round-analyses/{analysis_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Round Analysis Timeline
         * @description Return the verified immutable timeline for one completed analysis.
         */
        get: operations["get_round_analysis_timeline_v1_round_analyses__analysis_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/table-observations/{observation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Table Observation
         * @description Return one immutable table observation.
         */
        get: operations["get_table_observation_v1_table_observations__observation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisRoundRuleset
         * @description The fixed ruleset accepted by the round reconstruction contract.
         */
        AnalysisRoundRuleset: {
            /**
             * Name
             * @constant
             */
            name: "doko-normal";
            /**
             * Version
             * @constant
             */
            version: "v1";
        };
        /**
         * AnalysisRoundSetup
         * @description Explicit round setup supplied with an analysis request.
         */
        AnalysisRoundSetup: {
            /** Active Players */
            active_players: string[];
            /** Dealer */
            dealer: string;
            /**
             * Deck Variant
             * @constant
             */
            deck_variant: "doko-40-v1";
            /** First Trick Leader */
            first_trick_leader: string;
            /** Game Id */
            game_id: string;
            /** Round Id */
            round_id: string;
            ruleset: components["schemas"]["AnalysisRoundRuleset"];
        };
        /**
         * AnalysisSearchLimits
         * @description The three explicit Plan 0031 search limits.
         */
        AnalysisSearchLimits: {
            /** Max Hypotheses */
            max_hypotheses: number;
            /** Max Missing Plays */
            max_missing_plays: number;
            /** Max Search Nodes */
            max_search_nodes: number;
        };
        /**
         * AnalyzerMetadata
         * @description Analyzer identity recorded with each observation.
         */
        AnalyzerMetadata: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * AssociationCandidate
         * @description An uncertain link to an observed card in another observation.
         */
        AssociationCandidate: {
            /** Observed Card Id */
            observed_card_id: string;
            /** Score */
            score: number;
        };
        /**
         * CounterfactualArtifact
         * @description Identity and digest for one counterfactual runtime artifact.
         */
        CounterfactualArtifact: {
            /** Byte Length */
            byte_length: number;
            /** Relative Path */
            relative_path: string;
            /** Sha256 */
            sha256: string;
        };
        /**
         * CounterfactualObservedCardReferenceModel
         * @description An observed-card reference supplied by a counterfactual request.
         */
        CounterfactualObservedCardReferenceModel: {
            /** Observation Id */
            observation_id: string;
            /** Observed Card Id */
            observed_card_id: string;
        };
        /**
         * CounterfactualProbabilityOverrideModel
         * @description A candidate probability change supplied by a counterfactual request.
         */
        CounterfactualProbabilityOverrideModel: {
            /** Card */
            card: string;
            /** Observation Id */
            observation_id: string;
            /** Observed Card Id */
            observed_card_id: string;
            /** Probability */
            probability: number;
        };
        /**
         * EventMetadata
         * @description The causal event selected by the client decoder.
         */
        EventMetadata: {
            /** Emitted At Ms */
            emitted_at_ms: number;
            /** Event Time Ms */
            event_time_ms: number;
            /** Evidence Complete */
            evidence_complete: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityCandidate
         * @description One visual card identity ranked for an observed-card proposal.
         */
        IdentityCandidate: {
            /** Card */
            card: string;
            /** Probability */
            probability: number;
        };
        /**
         * ObservationSession
         * @description Session sequence metadata copied into an observation.
         */
        ObservationSession: {
            /** Event Sequence */
            event_sequence: number;
            /** Session Id */
            session_id: string;
        };
        /**
         * ObservationSource
         * @description The evidence package and optional snippet that produced an observation.
         */
        ObservationSource: {
            /** Package Id */
            package_id: string;
            /** Snippet Part Name */
            snippet_part_name?: string | null;
        };
        /**
         * ObservedCard
         * @description One anonymous visual card proposal inside one table observation.
         */
        ObservedCard: {
            /** Active Area Score */
            active_area_score?: number | null;
            /** Association Candidates */
            association_candidates?: components["schemas"]["AssociationCandidate"][] | null;
            /** Card Tracklet Id */
            card_tracklet_id?: string | null;
            /** Identity Candidates */
            identity_candidates: components["schemas"]["IdentityCandidate"][];
            /** Newly Visible Score */
            newly_visible_score?: number | null;
            /** Observed Card Id */
            observed_card_id: string;
            /** Presence Score */
            presence_score?: number | null;
        };
        /**
         * PackageMetadataResponse
         * @description Stored package metadata returned by the read endpoint.
         */
        PackageMetadataResponse: {
            event: components["schemas"]["EventMetadata"];
            /** Frames */
            frames: components["schemas"]["StoredFrameResponse"][];
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Missing Frame Targets Ms */
            missing_frame_targets_ms: number[];
            /**
             * Package Id
             * Format: uuid
             */
            package_id: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Schema Version */
            schema_version: string;
            session: components["schemas"]["SessionMetadata"];
            /**
             * State
             * @constant
             */
            state: "stored";
            /** Video Relative Path */
            video_relative_path: string | null;
            video_snippet: components["schemas"]["VideoSnippetManifest"] | null;
        };
        /**
         * PendingVideoUploadResponse
         * @description Response returned after a pending video receipt is published.
         */
        PendingVideoUploadResponse: {
            /** Byte Length */
            byte_length: number;
            /** Created */
            created: boolean;
            /** Media Facts */
            media_facts: {
                [key: string]: number | string;
            };
            /** Original Filename */
            original_filename: string;
            /** Received At Utc */
            received_at_utc: string;
            /** Sha256 */
            sha256: string;
            /** State */
            state: string;
            /** Upload Id */
            upload_id: string;
        };
        /**
         * RepositoryBundleFileResponse
         * @description Stored digest metadata for one canonical bundle member.
         */
        RepositoryBundleFileResponse: {
            /** Byte Length */
            byte_length: number;
            /** Sha256 */
            sha256: string;
        };
        /**
         * RepositoryBundleMetadataResponse
         * @description Canonical bundle metadata and member hashes.
         */
        RepositoryBundleMetadataResponse: {
            /** Files */
            files: {
                [key: string]: components["schemas"]["RepositoryBundleFileResponse"];
            };
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Recording Id */
            recording_id: string;
            /** Session Id */
            session_id: string;
            /** Source Asset Id */
            source_asset_id: string;
            /** Source Sha256 */
            source_sha256: string;
            /** State */
            state: string;
            /** Video Id */
            video_id: string;
        };
        /**
         * RepositoryBundleUploadResponse
         * @description Response returned after a bundle is accepted or found to be identical.
         */
        RepositoryBundleUploadResponse: {
            /** Created */
            created: boolean;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Recording Id */
            recording_id: string;
            /** State */
            state: string;
        };
        /**
         * RoundAnalysisCreateRequest
         * @description Client-created analysis request and its immutable input selection.
         */
        RoundAnalysisCreateRequest: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Evidence Package Ids */
            evidence_package_ids: string[];
            /** Recording Id */
            recording_id: string;
            /** Round Id */
            round_id: string;
            round_setup: components["schemas"]["AnalysisRoundSetup"];
            /**
             * Schema Version
             * @default round-analysis/v1
             * @constant
             */
            schema_version: "round-analysis/v1";
            search: components["schemas"]["AnalysisSearchLimits"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * RoundAnalysisResult
         * @description Compact terminal result returned by the analysis API.
         */
        RoundAnalysisResult: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Diagnostics */
            diagnostics: {
                [key: string]: unknown;
            };
            /** Focused Decisions */
            focused_decisions: {
                [key: string]: unknown;
            }[];
            /** Hypotheses */
            hypotheses: {
                [key: string]: unknown;
            }[];
            /** Input Artifact Id */
            input_artifact_id: string;
            /** Input Artifact Sha256 */
            input_artifact_sha256: string;
            /**
             * Reconstruction Status
             * @enum {string}
             */
            reconstruction_status: "resolved" | "ambiguous" | "incomplete" | "impossible";
            /** Result Artifact Id */
            result_artifact_id: string;
            /** Result Artifact Sha256 */
            result_artifact_sha256: string;
            /**
             * Terminal Status
             * @constant
             */
            terminal_status: "complete";
        };
        /**
         * RoundAnalysisStatus
         * @description Status document for one queued, running, or terminal analysis.
         */
        RoundAnalysisStatus: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Completed At */
            completed_at?: string | null;
            /** Completed Evidence Packages */
            completed_evidence_packages: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Recording Id */
            recording_id: string;
            result?: components["schemas"]["RoundAnalysisResult"] | null;
            /** Round Id */
            round_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Started At */
            started_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "analyzing_evidence" | "reconstructing" | "complete" | "failed";
            /** Total Evidence Packages */
            total_evidence_packages: number;
        };
        /**
         * RoundAnalysisTimeline
         * @description Strict backend-owned projection for one immutable completed analysis.
         */
        RoundAnalysisTimeline: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            artifact_hashes: components["schemas"]["TimelineArtifactHashes"];
            /** Diagnostics */
            diagnostics: {
                [key: string]: unknown;
            };
            /** Focused Decisions */
            focused_decisions: {
                [key: string]: unknown;
            }[];
            /** Hypotheses */
            hypotheses: components["schemas"]["TimelineHypothesis"][];
            /** Inferred Plays */
            inferred_plays: components["schemas"]["TimelineInferredPlay"][];
            /**
             * Reconstruction Status
             * @enum {string}
             */
            reconstruction_status: "resolved" | "ambiguous" | "incomplete" | "impossible";
            /** Recording Id */
            recording_id: string;
            /** Round Id */
            round_id: string;
            /** Rows */
            rows: components["schemas"]["TimelineEvidenceRow"][];
            /**
             * Schema Version
             * @default round-analysis-timeline/v1
             * @constant
             */
            schema_version: "round-analysis-timeline/v1";
            search: components["schemas"]["TimelineSearchLimits"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Warnings */
            warnings: components["schemas"]["TimelineWarning"][];
        };
        /**
         * RoundCounterfactualArtifacts
         * @description The request, input, and result artifacts for one counterfactual.
         */
        RoundCounterfactualArtifacts: {
            input: components["schemas"]["CounterfactualArtifact"];
            request: components["schemas"]["CounterfactualArtifact"];
            result: components["schemas"]["CounterfactualArtifact"];
        };
        /**
         * RoundCounterfactualCreateRequest
         * @description Client-created request for one immutable derived reconstruction.
         */
        RoundCounterfactualCreateRequest: {
            /** Candidate Probability Overrides */
            candidate_probability_overrides?: components["schemas"]["CounterfactualProbabilityOverrideModel"][];
            /**
             * Counterfactual Id
             * Format: uuid
             */
            counterfactual_id: string;
            /** Excluded Observation Ids */
            excluded_observation_ids?: string[];
            /** Excluded Observed Cards */
            excluded_observed_cards?: components["schemas"]["CounterfactualObservedCardReferenceModel"][];
            /**
             * Schema Version
             * @default round-analysis-counterfactual/v1
             * @constant
             */
            schema_version: "round-analysis-counterfactual/v1";
            /**
             * Source Analysis Id
             * Format: uuid
             */
            source_analysis_id: string;
            /** Source Input Sha256 */
            source_input_sha256: string;
            /** Source Result Sha256 */
            source_result_sha256: string;
        };
        /**
         * RoundCounterfactualResponse
         * @description The strict response for one stored counterfactual reconstruction.
         */
        RoundCounterfactualResponse: {
            artifacts: components["schemas"]["RoundCounterfactualArtifacts"];
            /**
             * Counterfactual Id
             * Format: uuid
             */
            counterfactual_id: string;
            request: components["schemas"]["RoundCounterfactualCreateRequest"];
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /**
             * Schema Version
             * @default round-analysis-counterfactual-response/v1
             * @constant
             */
            schema_version: "round-analysis-counterfactual-response/v1";
            /**
             * Source Analysis Id
             * Format: uuid
             */
            source_analysis_id: string;
        };
        /**
         * SessionMetadata
         * @description The capture session and logical event identity.
         */
        SessionMetadata: {
            /** Event Sequence */
            event_sequence: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * StoredFrameResponse
         * @description One frame returned by the package metadata endpoint.
         */
        StoredFrameResponse: {
            /** Actual Offset Ms */
            actual_offset_ms: number;
            /** Byte Length */
            byte_length: number;
            /**
             * Captured At Utc
             * Format: date-time
             */
            captured_at_utc: string;
            /** Content Type */
            content_type: string;
            /** Part Name */
            part_name: string;
            /** Relative Path */
            relative_path: string;
            /** Session Elapsed Ms */
            session_elapsed_ms: number;
            /** Sha256 */
            sha256: string;
            /** Target Offset Ms */
            target_offset_ms: number;
        };
        /**
         * TableObservation
         * @description One ordered, uncertain visual observation with no game claims.
         */
        TableObservation: {
            analyzer: components["schemas"]["AnalyzerMetadata"];
            /**
             * Calibration
             * @enum {string}
             */
            calibration: "fixture" | "uncalibrated" | "calibrated";
            /** Capabilities */
            capabilities: ("identity_candidates" | "presence_score" | "newly_visible_score" | "active_area_score" | "association_candidates" | "card_tracklets")[];
            /** Cards */
            cards?: components["schemas"]["ObservedCard"][];
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            };
            /** Observation Id */
            observation_id: string;
            /** Observed At Ms */
            observed_at_ms: number;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "table-observation/v1";
            session: components["schemas"]["ObservationSession"];
            source: components["schemas"]["ObservationSource"];
            /**
             * Status
             * @enum {string}
             */
            status: "observed" | "insufficient_evidence";
        };
        /**
         * TimelineArtifactHashes
         * @description Artifact identities recorded with one timeline projection.
         */
        TimelineArtifactHashes: {
            /** Input Artifact Id */
            input_artifact_id: string;
            /** Input Sha256 */
            input_sha256: string;
            /** Result Artifact Id */
            result_artifact_id: string;
            /** Result Sha256 */
            result_sha256: string;
        };
        /**
         * TimelineEvidenceRow
         * @description One ordered evidence and table-observation row.
         */
        TimelineEvidenceRow: {
            central_frame: components["schemas"]["TimelineFrame"] | null;
            /** Event Sequence */
            event_sequence: number;
            /** Event Time Ms */
            event_time_ms: number;
            /** Observation Id */
            observation_id: string;
            /** Observed At Ms */
            observed_at_ms: number;
            /**
             * Package Id
             * Format: uuid
             */
            package_id: string;
            table_observation: components["schemas"]["TableObservation"];
        };
        /**
         * TimelineFrame
         * @description The validated central frame descriptor for one evidence row.
         */
        TimelineFrame: {
            /** Actual Offset Ms */
            actual_offset_ms: number;
            /** Byte Length */
            byte_length: number;
            /**
             * Captured At Utc
             * Format: date-time
             */
            captured_at_utc: string;
            /**
             * Content Type
             * @constant
             */
            content_type: "image/jpeg";
            /** Height */
            height: number;
            /**
             * Package Id
             * Format: uuid
             */
            package_id: string;
            /** Part Name */
            part_name: string;
            /** Sha256 */
            sha256: string;
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /**
         * TimelineHypothesis
         * @description One ranked reconstruction interpretation with its action mapping.
         */
        TimelineHypothesis: {
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[];
            /** Gameplay */
            gameplay: {
                [key: string]: unknown;
            };
            /** Ignored Observed Card Ids */
            ignored_observed_card_ids: string[];
            /** Inferred Plays */
            inferred_plays: components["schemas"]["TimelineInferredPlay"][];
            /** Missing Play Indices */
            missing_play_indices: number[];
            /** Rank */
            rank: number;
            /** Score Breakdown */
            score_breakdown: {
                [key: string]: unknown;
            };
            /** Source Observation Ids */
            source_observation_ids: string[];
            /** Source Observed Card Ids */
            source_observed_card_ids: string[];
            /** Total Score */
            total_score: number;
        };
        /**
         * TimelineInferredPlay
         * @description An inferred play anchored to neighboring evidence rows.
         */
        TimelineInferredPlay: {
            /** After Observation Id */
            after_observation_id?: string | null;
            /** Before Observation Id */
            before_observation_id?: string | null;
            /** Card */
            card: string;
            /** Play Index */
            play_index: number;
            /** Player */
            player: string;
            /**
             * Position
             * @enum {string}
             */
            position: "before" | "between" | "after";
        };
        /**
         * TimelineSearchLimits
         * @description Search limits copied from the immutable reconstruction result.
         */
        TimelineSearchLimits: {
            /** Max Hypotheses */
            max_hypotheses: number;
            /** Max Missing Plays */
            max_missing_plays: number;
            /** Max Search Nodes */
            max_search_nodes: number;
        };
        /**
         * TimelineWarning
         * @description A non-fatal condition that the timeline must show to an operator.
         */
        TimelineWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * UploadResponse
         * @description The response returned after a package is accepted.
         */
        UploadResponse: {
            /** Created */
            created: boolean;
            /**
             * Package Id
             * Format: uuid
             */
            package_id: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /**
             * State
             * @constant
             */
            state: "stored";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VideoSnippetManifest
         * @description One optional event-relative encoded video snippet declaration.
         */
        VideoSnippetManifest: {
            /**
             * Byte Length
             * @default 0
             */
            byte_length: number;
            /** Capture Complete */
            capture_complete: boolean;
            /** Container */
            container?: "mp4" | null;
            /** Content Type */
            content_type?: "video/mp4" | null;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** End Offset Ms */
            end_offset_ms?: number | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /**
             * Height
             * @default 0
             */
            height: number;
            /** Nominal Frame Rate */
            nominal_frame_rate?: number | null;
            /** Part Name */
            part_name?: string | null;
            /** Sha256 */
            sha256?: string | null;
            /** Start Offset Ms */
            start_offset_ms?: number | null;
            /** Video Codec */
            video_codec?: "h264" | null;
            /**
             * Width
             * @default 0
             */
            width: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_evidence_package_v1_evidence_packages__package_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_evidence_package_v1_evidence_packages__package_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_package_table_observations_v1_evidence_packages__package_id__table_observations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableObservation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_video_snippet_v1_evidence_packages__package_id__video_snippet_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_video_v1_pending_videos__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingVideoUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_pending_video_v1_pending_videos__upload_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingVideoUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_bundle_v1_repository_bundles__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryBundleMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_repository_bundle_v1_repository_bundles__recording_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryBundleUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_round_analysis_v1_round_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundAnalysisCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundAnalysisStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_analysis_v1_round_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundAnalysisStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_round_counterfactual_v1_round_analyses__analysis_id__counterfactuals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundCounterfactualCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundCounterfactualResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_counterfactual_v1_round_analyses__analysis_id__counterfactuals__counterfactual_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
                counterfactual_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundCounterfactualResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_analysis_frame_v1_round_analyses__analysis_id__evidence_packages__package_id__frames__part_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
                package_id: string;
                part_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_analysis_timeline_v1_round_analyses__analysis_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundAnalysisTimeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_table_observation_v1_table_observations__observation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableObservation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
